
import java.io.IOException;
import java.io.PrintWriter;
import java.net.Socket;
import java.util.Scanner;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author a-a-robbins
 */
public class UserLandingPage extends javax.swing.JDialog {
    private static final String LOGON = "LogOn"; 
    private String address; 

    /**
     * Creates new form UserLandingPage
     */
    public UserLandingPage(java.awt.Frame parent, boolean modal, String address) {
        super(parent, modal);
        initComponents();
        this.address = address; 
    }
    
    public String getUsername() {
        String name = usernameField.getText(); 
        return name; 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        welcomeLabel = new javax.swing.JLabel();
        userpassPanel = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        usernameField = new javax.swing.JTextField();
        aboutPanel = new javax.swing.JPanel();
        learnMoreLabel1 = new javax.swing.JLabel();
        learnMoreLabel2 = new javax.swing.JLabel();
        aboutButton = new javax.swing.JButton();
        learnMoreLabel3 = new javax.swing.JLabel();
        makeAccountPanel = new javax.swing.JPanel();
        noAccountLabel = new javax.swing.JLabel();
        registerButton = new javax.swing.JButton();
        logInButtonPanel = new javax.swing.JPanel();
        logInButton = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jLabel3.setText("jLabel3");

        jLabel5.setText("jLabel5");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        welcomeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        welcomeLabel.setText("Welcome!");

        usernameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        usernameLabel.setText("username: ");

        passwordLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passwordLabel.setText("password: ");

        passwordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordFieldKeyPressed(evt);
            }
        });

        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout userpassPanelLayout = new javax.swing.GroupLayout(userpassPanel);
        userpassPanel.setLayout(userpassPanelLayout);
        userpassPanelLayout.setHorizontalGroup(
            userpassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userpassPanelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(userpassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(userpassPanelLayout.createSequentialGroup()
                        .addComponent(passwordLabel)
                        .addGap(18, 18, 18)
                        .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(userpassPanelLayout.createSequentialGroup()
                        .addComponent(usernameLabel)
                        .addGap(18, 18, 18)
                        .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        userpassPanelLayout.setVerticalGroup(
            userpassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userpassPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(userpassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(userpassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        learnMoreLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        learnMoreLabel1.setText("Not sure you want to be part of this awesomeness yet? ");

        learnMoreLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        learnMoreLabel2.setText("Check out our ");

        aboutButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        aboutButton.setText("ABOUT");
        aboutButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                aboutButtonKeyPressed(evt);
            }
        });

        learnMoreLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        learnMoreLabel3.setText("section to learn more!");

        javax.swing.GroupLayout aboutPanelLayout = new javax.swing.GroupLayout(aboutPanel);
        aboutPanel.setLayout(aboutPanelLayout);
        aboutPanelLayout.setHorizontalGroup(
            aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutPanelLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(learnMoreLabel1)
                    .addGroup(aboutPanelLayout.createSequentialGroup()
                        .addComponent(learnMoreLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aboutButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(learnMoreLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        aboutPanelLayout.setVerticalGroup(
            aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(learnMoreLabel1)
                .addGap(18, 18, 18)
                .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(learnMoreLabel2)
                    .addComponent(aboutButton)
                    .addComponent(learnMoreLabel3))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        noAccountLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        noAccountLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        noAccountLabel.setText("No account? Make one ");

        registerButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        registerButton.setText("HERE");
        registerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerButtonMouseClicked(evt);
            }
        });
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout makeAccountPanelLayout = new javax.swing.GroupLayout(makeAccountPanel);
        makeAccountPanel.setLayout(makeAccountPanelLayout);
        makeAccountPanelLayout.setHorizontalGroup(
            makeAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, makeAccountPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(noAccountLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(registerButton)
                .addContainerGap())
        );
        makeAccountPanelLayout.setVerticalGroup(
            makeAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(makeAccountPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(makeAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerButton)
                    .addComponent(noAccountLabel))
                .addContainerGap())
        );

        logInButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        logInButton.setText("Log In");
        logInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout logInButtonPanelLayout = new javax.swing.GroupLayout(logInButtonPanel);
        logInButtonPanel.setLayout(logInButtonPanelLayout);
        logInButtonPanelLayout.setHorizontalGroup(
            logInButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logInButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logInButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        logInButtonPanelLayout.setVerticalGroup(
            logInButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logInButtonPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(logInButton)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(welcomeLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(makeAccountPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(logInButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aboutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userpassPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(welcomeLabel)
                .addGap(26, 26, 26)
                .addComponent(userpassPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(makeAccountPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logInButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(aboutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        //create new registration dialog
        RegistrationDialog dialog = new RegistrationDialog(new javax.swing.JFrame(), true, address);
        
        //in case window is exited instead of going through registration process
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                         dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
                    }
                });
        
                dialog.setVisible(true); 
                
    }//GEN-LAST:event_registerButtonActionPerformed

    private void registerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerButtonMouseClicked
                }//GEN-LAST:event_registerButtonMouseClicked

    private void logInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInButtonActionPerformed
       
       try { 
            //create a host, localhost = local machine (no need for IP address)
            String host = address; 

            //connect to specified host on Server port#
            Socket sock = new Socket(host, 2001); 
            
            //create IO stream from socket
            Scanner in = new Scanner(sock.getInputStream()); 
            
            PrintWriter out = new PrintWriter(sock.getOutputStream(), true); 
            
                    
            //create protocol
            out.println(LOGON); 
            out.println(usernameField.getText()); 
            out.println(passwordField.getText());  
            
            String result = in.nextLine(); 
            JOptionPane.showMessageDialog(UserLandingPage.this, result); 
            
            //close dialog but not system
            if(result.equals("valid log on")) { 
                this.dispose(); 
            }      
            
       }
       
       catch (IOException e) {
           //generate error message, perhaps write to log later
           System.err.println("IOEXCEPTION in logInButtonAction: " + e.getMessage());
       }
        
    }//GEN-LAST:event_logInButtonActionPerformed

    private void aboutButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aboutButtonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_aboutButtonKeyPressed

    private void passwordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordFieldKeyPressed
        if(evt.equals("Enter")) {
            try { 
            //create a host, localhost = local machine (no need for IP address)
            String host = address; 

            //connect to specified host on Server port#
            Socket sock = new Socket(host, 2001); 
            
            //create IO stream from socket
            Scanner in = new Scanner(sock.getInputStream()); 
            
            PrintWriter out = new PrintWriter(sock.getOutputStream(), true); 
            
                    
            //create protocol
            out.println(LOGON); 
            out.println(usernameField.getText()); 
            out.println(passwordField.getText());  
            
            String result = in.nextLine(); 
            JOptionPane.showMessageDialog(UserLandingPage.this, result); 
            
            //close dialog but not system
            if(result.equals("valid log on")) { 
                this.dispose(); 
            }      
            
       }
       
       catch (IOException e) {
           //generate error message, perhaps write to log later
           System.err.println("IOEXCEPTION in passwordKeyFieldPressed: " + e.getMessage());
       }
        }
    }//GEN-LAST:event_passwordFieldKeyPressed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutButton;
    private javax.swing.JPanel aboutPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel learnMoreLabel1;
    private javax.swing.JLabel learnMoreLabel2;
    private javax.swing.JLabel learnMoreLabel3;
    private javax.swing.JButton logInButton;
    private javax.swing.JPanel logInButtonPanel;
    private javax.swing.JPanel makeAccountPanel;
    private javax.swing.JLabel noAccountLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton registerButton;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JPanel userpassPanel;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
